// 选中的人 或者 状态：商机来源，商机状态，行业，汇款方式等
export const SELECTED_MEMBER = 'SELECTED_MEMBER'
export const SELECTED_POST = 'SELECTED_POST'
export const SELECTED_STATE = 'SELECTED_STATE'
export const GETXSUSERLIST = 'GETXSUSERLIST'

export const GETDEPARTMENTLIST = 'GETDEPARTMENTLIST'

export const GETUSERDETAIL = 'GETUSERDETAIL'

export const INITCOMPANYOBJ = 'INITCOMPANYOBJ'
export const CHANGECOMPANY = 'CHANGECOMPANY'

export const GETUSERLISTBYDEPARTID = 'GETUSERLISTBYDEPARTID'

export const FLAGFORINIT = 'FLAGFORINIT'



