const state = {
    selectedMember:[],
    selectedState:[
        {
            value:"",
            name:"商机来源",
            id:"0"
        },
        {
            value:"",
            name:"商机状态",
            id:"1"
        },
        {
            value:"",
            name:"拜访方式",
            id:"2"
        },
        {
            value:"",
            name:"汇款方式",
            id:"3"
        },
        {
            value:"",
            name:"区域",
            id:"4"
        },
        {
            value:"",
            name:"规模",
            id:"5"
        },
        {
            value:"",
            name:"性质",
            id:"6"
        },
        {
            value:"",
            name:"性质",
            id:"7"
        },
        {
            value:"",
            name:"行业",
            id:"7"
        },
        {
            value:"",
            name:"所属栏目",
            id:"8",
            boardId:''
        }
    ],
    storeUserList:[],
    storeDepartMentList:[],
    selectedPost:[],
    userDetail:{},
    companyState:'0',
    departUserListData:{},
    departUserList:[],
    userInitData:{},
    flagForInit:false,
    userReportData:{},
}

export default state
