export const GETSMSLISTS = 'GETSMSLISTS';
export const ADDSMSRECORD = 'ADDSMSRECORD';
export const DELETESMSRECORD = 'DELETESMSRECORD';
export const SENDSMS = 'SENDSMS';
export const ADDSMSFROMWEB = 'ADDSMSFROMWEB';


