export const PAYMENT_SUM = 'PAYMENT_SUM'
export const PAYMENT_LIST = 'PAYMENT_LIST'
export const PAYMENT_DETAIL = 'PAYMENT_DETAIL'
export const ADD_PAYMENT = 'ADD_PAYMENT'
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT'
export const RECEIVE_PAYMENT = 'RECEIVE_PAYMENT'
export const PAY_INSTALL_LIST = 'PAY_INSTALL_LIST'

