const sourceData=[
    {
        id:"0",
        title:"电话来访",
        flag:false,
    },
    {
        id:"1",
        title:"客户介绍",
        flag:false,
    },
    {
        id:"2",
        title:"代理商",
        flag:false,
    },
    {
        id:"3",
        title:"合作伙伴",
        flag:false,
    },
    {
        id:"4",
        title:"公开招标",
        flag:false,
    },
    {
        id:"5",
        title:"互联网",
        flag:false,
    },
    {
        id:"6",
        title:"自主开发",
        flag:false,
    },
    {
        id:"7",
        title:"其他",
        flag:false,
    },
];
const statusData=[//商机状态1
    {
        id:"1",
        title:"初期沟通",
        flag:false,
    },
    {
        id:"2",
        title:"立项评估",
        flag:false,
    },
    {
        id:"3",
        title:"需求分析",
        flag:false,
    },
    {
        id:"4",
        title:"方案指定",
        flag:false,
    },
    {
        id:"5",
        title:"招投标/竞争",
        flag:false,
    },
    {
        id:"6",
        title:"商务谈判",
        flag:false,
    },
    {
        id:"7",
        title:"合同签约",
        flag:false,
    }
]
const patterData=[//拜访方式2
    {
        id:"1",
        title:"电话拜访",
        flag:false,
    },
    {
        id:"2",
        title:"现场摆放",
        flag:false,
    },
    {
        id:"3",
        title:"其他",
        flag:false,
    }
];
const pushMoney=[//汇款方式3
    {
        id:"1",
        title:"现金",
        flag:false,
    },
    {
        id:"2",
        title:"转账",
        flag:false,
    },
    {
        id:"3",
        title:"汇款",
        flag:false,
    }
];
const addressList=[//区域4
    {
        id:"1",
        title:"北方区",
        flag:false,
    },
    {
        id:"2",
        title:"南方区",
        flag:false,
    },
    {
        id:"3",
        title:"西部区",
        flag:false,
    },
    {
        id:"4",
        title:"华东区",
        flag:false,
    },
    {
        id:"5",
        title:"港澳台",
        flag:false,
    },
    {
        id:"6",
        title:"华北区",
        flag:false,
    }
];
const scaleData=[//规模5
    {
        id:"1",
        title:"20人以下",
        flag:false,
    },
    {
        id:"2",
        title:"20-50人",
        flag:false,
    },
    {
        id:"3",
        title:"51-100人",
        flag:false,
    },
    {
        id:"4",
        title:"101-500人",
        flag:false,
    },
    {
        id:"5",
        title:"501-1000人",
        flag:false,
    },
    {
        id:"6",
        title:"一千人以上",
        flag:false,
    }
];
const natureData=[//性质6
    {
        id:"1",
        title:"有限责任公司",
        flag:false,
    },
    {
        id:"2",
        title:"股份邮箱公司",
        flag:false,
    },
    {
        id:"3",
        title:"国有独资公司",
        flag:false,
    },
    {
        id:"4",
        title:"个人独资公司",
        flag:false,
    },
    {
        id:"5",
        title:"个体工商户",
        flag:false,
    },
    {
        id:"6",
        title:"合作企业",
        flag:false,
    },
    {
        id:"7",
        title:"外商投资公司",
        flag:false,
    },
    {
        id:"8",
        title:"私营企业",
        flag:false,
    },
    {
        id:"9",
        title:"自营食堂",
        flag:false,
    },
    {
        id:"10",
        title:"酒店餐饮",
        flag:false,
    },
    {
        id:"11",
        title:"团膳公司",
        flag:false,
    },
    {
        id:"12",
        title:"团购客户",
        flag:false,
    },
    {
        id:"13",
        title:"经销商",
        flag:false,
    },
    {
        id:"14",
        title:"商超",
        flag:false,
    },
    {
        id:"15",
        title:"其他",
        flag:false,
    }
];
const industryData=[//行业7
    {
        id:"1",
        title:"高科技",
        flag:false,
    },
    {
        id:"2",
        title:"快消品",
        flag:false,
    },
    {
        id:"3",
        title:"互联网",
        flag:false,
    },
    {
        id:"4",
        title:"家居建材",
        flag:false,
    },
    {
        id:"5",
        title:"家电",
        flag:false,
    },
    {
        id:"6",
        title:"综合",
        flag:false,
    },
    {
        id:"7",
        title:"其他",
        flag:false,
    }
];
const columnData=[//所属栏目8
    {
        id:"1",
        title:"X有限公司",
        flag:false,
    },
    {
        id:"2",
        title:"XX有限公司",
        flag:false,
    },
    {
        id:"3",
        title:"XXX有限公司",
        flag:false,
    },
    {
        id:"4",
        title:"XXXX有限公司",
        flag:false,
    }
];
module.exports={
    sourceData,
    statusData,
    patterData,
    pushMoney,
    addressList,
    scaleData,
    natureData,
    industryData,
    columnData
  };
  