export const PROLIST='PROLIST'
export const PROTASKINFO='PROTASKINFO'
export const PROTASKDETAIL='PROTASKDETAIL'  
export const UPDATEPRO='UPDATEPRO'
export const SUBPRO='SUBPRO'
export const ONLINEPRO='ONLINEPRO'
export const UPLOADFILE='UPLOADFILE'
export const SHAREPRO='SHAREPRO'


