export const QUERYREVIEW = 'QUERYREVIEW';
export const SAVEREVIEW = 'SAVEREVIEW';
export const INITIATEREPORT = 'INITIATEREPORT';
export const CLEAR_INITIATEREPORT = 'CLEAR_INITIATEREPORT';
export const RECEIVEDREPORT = 'RECEIVEDREPORT';
export const CLEAR_RECEIVEDREPORT = 'CLEAR_RECEIVEDREPORT';
export const VIEWREPORT = 'VIEWREPORT';
export const CLEAR_VIEWREPORT = 'CLEAR_VIEWREPORT';
export const REPORTCOMMENT = 'REPORTCOMMENT';
export const CLEAR_REPORTCOMMENT = 'CLEAR_REPORTCOMMENT';
export const REPORTCOMMENTADD = 'REPORTCOMMENTADD';
export const ADDREPORT = 'ADDREPORT';















