export const RECOMLIST='RECOMLIST'
export const RECOMSERVAUDPASS='RECOMSERVAUDPASS'
export const ADDRECOMAUDFLOW='ADDRECOMAUDFLOW'
export const RECOMTASKINFO='RECOMTASKINFO'
export const RECOMTASKDETAIL='RECOMTASKDETAIL'  
export const UPDATERECOM='UPDATERECOM'
export const SUBRECOM='SUBRECOM'
export const ONLINERECOM='ONLINERECOM'
export const UPLOADFILE='UPLOADFILE'
export const RECOMMENTFIELDS='RECOMMENTFIELDS'
export const RECOMMENDTASKFIELDS='RECOMMENDTASKFIELDS'
export const GETTASKSTATUSLISTS='GETTASKSTATUSLISTS'
export const GETRECOMMENDSERVICEAUDITPASSLISTS='GETRECOMMENDSERVICEAUDITPASSLISTS'
export const ADDTASKRECOMMENDAUDITFLOW='ADDTASKRECOMMENDAUDITFLOW'



