export const USERLOGIN = 'USERLOGIN'
export const UPDATEWEBUSERPWD = 'UPDATEWEBUSERPWD'
export const CHECKUSER_REGIST = 'CHECKUSER_REGIST'
export const REG_COMPANY = 'REG_COMPANY'
export const GET_DEMO_INDUSTRY = 'GET_DEMO_INDUSTRY'
export const DEMO_LOGIN = 'DEMO_LOGIN';
export const DEPARTMENTLIST = 'DEPARTMENTLIST';

