export const CHANGE_PAGETYPE = 'CHANGE_PAGETYPE'

export const TALENTLIST = 'TALENTLIST'
export const LIST = 'LIST'
export const CORRECT_TALENTLIST = 'CORRECT_TALENTLIST'
export const CLEAR_TALENTLIST = 'CLEAR_TALENTLIST'

export const RESUMEDETAIL = 'RESUMEDETAIL'
export const CLEAR_RESUMEDETAIL = 'CLEAR_RESUMEDETAIL'

export const ADDSUBSCRIBE = 'ADDSUBSCRIBE'
export const REMOVESUBSCRIBE = 'REMOVESUBSCRIBE'
export const BUYSUBSCRIBE = 'BUYSUBSCRIBE'
export const REDUCE_RESUME_BALANCE = 'REDUCE_RESUME_BALANCE'
export const CLEAR_SUBSCRIBE = 'CLEAR_SUBSCRIBE'

export const SEARCH_VALUE = 'SEARCH_VALUE'