export const CONTRACT_RECORD = 'CONTRACT_RECORD'
export const CONTRACT_LIST = 'CONTRACT_LIST'
export const CONTRACT_DETAIL = 'CONTRACT_DETAIL'
export const CONTRACT_DETAIL_BYNUM = 'CONTRACT_DETAIL_BYNUM'
export const ADD_CONTRACT = 'ADD_CONTRACT'
export const UPDATE_CONTRACT = 'UPDATE_CONTRACT'

