const state = {
    talkAboutData: {},
    phoneListData:{},
    queryNameListData:{},
    addAiTaskData:{},
    seatsData:{},
    queryListData:{},
    allTaskStartData:{},
    allTaskStatusData:{},
    allTaskEndData:{},
    industryScreeningData:{},
    statisticalData:{},
    taskPhoneListData:{},
    taskPhoneDetaiData:{},
    startTaskData:{},
    pauseTaskData:{},
    delTaskData:{},
    addCustomerData:{},
    readTaskData:{},
    intentionGradeData:{},
    outboundWayData:{},
    aiIsData:{},
    customerResultData:{}
} 
export default state
